### PR TITLE
Webpack compatibility

### PR DESCRIPTION
**Pull request by traj**
If you install this module using npm,  this file allows you to require using this syntax
 `require('angular-contentful');`

### CODE REVIEW

**Comment by jvandemo** [comment]
@traj &mdash; Thank you, what is the purpose of assigning `contentful` to `module.exports`?

Thanks in advance!

**Comment by traj** [comment]
@jvandemo - I'm using [this generator](https://github.com/FountainJS/generator-fountain-webapp) with angular 1 + webpack. Adding this index.js to `angular-contentful` in my node_modules folder allowed me to import `angular-contentful` the same way the other modules are imported and works with both the `serve` and `dist` gulp tasks. I tried `require('angular-contentful/dist/angular-contentful')`but it did not work.

**Comment by jvandemo** [comment]
@traj &mdash; Is your code available online? I tried installing the generator, but it doesn't work. Thanks!

**Comment by traj** [comment]
Sure. Try this out:
[fountain js generator + angular contentful example project](https://github.com/traj/angular-contentful-example)

**Comment by jvandemo** [comment]
@traj &mdash; Can you try adding a `module` property to the `package.json` of your angular-contentful package in your node_modules directory, so you get:

```javascript
"main": "dist/angular-contentful.js",
"module": "dist/angular-contentful.js",
```

Webpack uses the `module` property of `package.json`.

If you can confirm that it works, we can update the `package.json` file in this repository 👍

**Comment by traj** [comment]
Thanks, that works. I've updated the PR

**Comment by jvandemo** [comment]
@traj &mdash; Perfect, thank you for your contribution! 👍

**Pull request merged**
