### PR TITLE
Enabled multiple space configuration

### PR DESCRIPTION
**Pull request by vuk**
Idea behind this is to enable multiple space initialization. 
Basically instead of doing 
```javascript

    contentfulProvider.setOptions({
        space: 'yourSpace',
        accessToken: 'yourAccessToken'
    });

```

You can do 

```javascript

    contentfulProvider.setOptions(
        'default': {
          space: 'first_space',
          accessToken: 'first_token',
        },
        'another': {
          space: 'second_space',
          accessToken: 'second_token',
        });
```

Although the first one will still work as it will default to `default` and if you use package as it was originally it would still work as expected

### CODE REVIEW

**Comment by jvandemo** [comment]
@vuk &mdash; Thank you, this looks very promising!

Can you please add a section to the README.md to explain how it works including example code as you have listed above?

Thanks in advance for your great effort!

**Comment by vuk** [comment]
I've updated Readme file. Please check if it fits, although I don't think I missed anything major.

**Comment by jvandemo** [comment]
@vuk &mdash; Thank you for your quick follow-up.

> Defaults to `default` key, or if only one space settings are passed it will use that one.

Can you please add an example of how to pass in a key and how to pass in space settings?

Then I can review everything and merge if all works as expected.

Thanks again! 👍

**Comment by vuk** [comment]
It's updated now. I gave a short sample how methods can be called with option keys with note that parameter can be omitted. I gave a sample initialization of provider with alternative call to setOptions in Usage section as well.

**Comment by jvandemo** [comment]
@vuk &mdash; Thank you, I should be able to merge your PR later this week 👍

**Comment by vuk** [comment]
Great, thanks. If it's not too big of a hassle, can you let me know when you merge if it will be in release 2.1.1 or 2.2.0?

**Comment by jvandemo** [comment]
If everything is backwards compatible, the new version will be 2.2.0.

Is something may break existing code, the new version will be 3.0.0.

From what I can see now, it will thus be 2.2.0. Hope that helps!

**Comment by vuk** [comment]
Yes. I aimed to keep backwards compatibility completely

**Comment by vuk** [comment]
Just to check up if there is a time frame for next release, as I'm using it in a project :)

**Comment by jvandemo** [comment]
@vuk &mdash; Your changes have been merged and released as v2.2.0.

Thank you for your contribution! 👍 

PS: would you be interested in adding support for multiple spaces to the directives as well? Thanks again!

**Comment by vuk** [comment]
I'll work on adding another parameter to directives in next few days

**Comment by jvandemo** [comment]
Brilliant! Thank you, Vuk, much appreciated! 👍  :1st_place_medal:

**Pull request merged**
